name: Run Bot

on:
  schedule:
    - cron: '47 15 * * *'  # Запуск каждый день в 15:40 UTC
  workflow_dispatch:  # Позволяет вручную запустить workflow из вкладки Actions

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install python-telegram-bot

      - name: Run bot
        run: |
          python /home/Wwuire/my_bot.py
